name: Playwright Tests

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      UI_BASE_URL: https://mini-app-rep-git-87c73e-mukeshkumarbalusamioutlookcoms-projects.vercel.app
      API_BASE_URL: https://miniapp-repo-staging.onrender.com/api/v1/notes
      VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_BYPASS_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30